name: 'Lock Threads'

on:
  schedule:
    - cron: '0 * * * *'

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5.0.1
        with:
          github-token: ${{ github.token }}
          issue-comment: 'This issue is now locked and considered resolved. If you have questions or inquiries, you may start a new issue.'
          issue-inactive-days: '30'
          issue-lock-reason: 'resolved'
          log-output: true
